tests:
  - tag: "Scenario #1" # identifier for reporting
    pipeline: "" # empty for any
    verbose: True # set to True for more verbose information
    uppaalModel: "fixtures/01/model.xml" # uppaal Model used for this test
    resultsDirectory: "testit_tests/results/" # where to store results inside TestIt docker w.r.t. sharedDirectory (i.e., sharedDirectory="/testit/" and resultsDirectory="testit_tests/results/" => results will be stored in "/testit/testit_tests/results")
    launch: "(roslaunch testit_dtron_tutorials testit_adapter_coverage.launch waypoints:=\"[[sharedDirectory]]testit_tests/fixtures/01/waypoints.yaml\" coverage_output_directory:=\"[[sharedDirectory]][[resultsDirectory]]\" &); (sleep 10 && rosrun testit_dtron run_dtron_test.sh [[sharedDirectory]]testit_tests/[[uppaalModel]])" # how to execute this test (run command) in TestIt container, if empty, then assumed that test is not explicitly executed (already started at runSUT and oracle is used to determine pass/fail)
    oracle: "[[sharedDirectory]]testit_tests/tests/01/oracle/oracle.py 24.1 6.52" # determining whether pass/fail, if empty = "launch" execution result will be used to determine pass/fail
    timeout: 60 # time in seconds for timeout (0 for no timeout)
    timeoutVerdict: False # if timeout occurs, declare the test as this (False = fail, True = success)
    postCommand: "echo 'Test finished!'" # it is possible to execute shell commands after running the test
    bagMaxSplits: "" # empty = use default
    bagDuration: "" # empty = use default

configuration:
  dataDirectory: "$(rospack find testit)/data/" # Where to store coverage files, bag files etc.
  bringupSUT: "" # how to bring up a pipeline server/docker SUT (general case), you can use "[[]]" for replacing
  bringupSUTDelay: 0 # duration to wait after command
  bringupSUTTimeout: 1 # seconds (0 for no timeout, but you have to specify bringup_finish_trigger then or tests will not be run)
  bringupSUTFinishTrigger: "-" # command to test whether startup is finished, "-" = no trigger
  runSUT: "docker run --rm --net=rosnetwork --env ROS_HOSTNAME=[[masterHost]] --env ROS_MASTER_URI=http://[[masterHost]]:11311 --name [[masterHost]] -dt testit_dtron_tb_coverage_sut:latest /bin/bash -c \"source /catkin_ws/devel/setup.bash && roslaunch robots_stage stage.launch _world_file:=/catkin_ws/src/robots_stage/maps/4korrus/4korrus.world map_file:=/catkin_ws/src/robots_stage/maps/4korrus/4korrus.yaml initial_x:=28.6 initial_y:=4.0 initial_a:=0.0\"" # run SUT 
  runSUTDelay: 10 # duration to wait for SUT to come up (roscore initialization)
  runSUTTimeout: 5
  runSUTFinishTrigger: "-"
  stopSUT: "docker kill [[masterHost]]"
  stopSUTDelay: 5 # duration to wait after stopping the SUT
  stopSUTTimeout: 0
  stopSUTFinishTrigger: "-"
  teardownSUT: "" # how to clean up after finishing (shut down server/docker) (general case)
  teardownSUTDelay: 0 # duration to wait after teardown
  teardownSUTTimeout: 5
  teardownSUTFinishTrigger: "-"
  bringupTestIt: "" # bring up the pipeline server (in the cloud for example)
  bringupTestItDelay: 0 # duration to wait after command
  bringupTestItTimeout: 1
  bringupTestItFinishTrigger: "-"
  runTestIt: "docker run --rm --volume=[[testItVolume]]:[[sharedDirectory]] --net=rosnetwork --env ROS_VERSION=[[testItRosVersion]] --env ROS_HOSTNAME=[[testItHost]] --env ROS_MASTER_URI=http://[[masterHost]]:11311 --name [[testItHost]] -dt testit_dtron_tb_coverage_testit:latest /catkin_ws/spread/sbin/spread" # how to bring up a pipeline TestIt (general case), you can use "[[]]" for replacing 
  runTestItDelay: 5 # duration to wait after command
  runTestItTimeout: 5
  runTestItFinishTrigger: "-"
  stopTestIt: "docker kill [[testItHost]]" # general case pipeline stopping
  stopTestItDelay: 0 # duration to wait after command
  stopTestItTimeout: 5
  stopTestItFinishTrigger: "-"
  teardownTestIt: ""
  teardownTestItDelay: 0 # duration to wait after command
  teardownTestItTimeout: 5 # empty string = use default
  teardownTestItFinishTrigger: "-" # command to test whether startup is finished, "-" = no trigger
  bagEnabled: False # True=rosbag record, False=don't bag
  bagMaxSplits: 5 # total bag duration = maxsplits*duration
  bagDuration: 15 # seconds

pipelines:
  - tag: "Pipeline #1" # identifier for reporting
    testItRosVersion: "lunar"
    sutConnection: "-" # (e.g., "user@pipe1.domain.com"). "-" means no command (ssh, scp) wrapping, execute docker and other commands on localhost. Note that bringup/teardown are not wrapped. Run/stop + test commands are wrapped
    testItConnection: "-" # see above
    masterHost: "sut1"
    testItHost: "testit1"
    masterIP: "-" # where SUT roscore is running (used if masterHost is not defined) ("-" means none)
    testItIP: "-" # where TestIt docker container is running (used if testitHost is not defined) ("-" means none)
    testItVolume: "$(rospack find testit_dtron_tutorials)/turtlebot_coverage/" # where TestIt volume is located (test scenarios + bags are stored there) at the [[testItConnection]] host.
    sharedDirectory: "/testit/" # shared volume for TestIt docker container (shared files with host)
    bringupSUT: "" # empty string = use default
    bringupSUTDelay: ""
    bringupSUTTimeout: "" # empty string = use default
    bringupSUTFinishTrigger: "" # empty string = use default
    runSUT: "" # empty string = use default
    runSUTDelay: ""
    runSUTTimeout: ""
    runSUTFinishTrigger: ""
    stopSUT: ""
    stopSUTDelay: ""
    stopSUTTimeout: ""
    stopSUTFinishTrigger: ""
    teardownSUT: "" # custom teardown for this pipeline
    teardownSUTDelay: ""
    teardownSUTTimeout: "" # empty string = use default
    teardownSUTFinishTrigger: "" # empty string = use default
    bringupTestIt: "" # empty string = use default
    bringupTestItDelay: ""
    bringupTestItTimeout: "" # empty string = use default
    bringupTestItFinishTrigger: "" # empty string = use default
    runTestIt: "" # empty string = use default
    runTestItDelay: ""
    runTestItTimeout: ""
    runTestItFinishTrigger: ""
    stopTestIt: ""
    stopTestItDelay: ""
    stopTestItTimeout: ""
    stopTestItFinishTrigger: ""
    teardownTestIt: "" # custom teardown for this pipeline
    teardownTestItDelay: "" # duration to wait after command
    teardownTestItTimeout: "" # empty string = use default
    teardownTestItFinishTrigger: "" # empty string = use default
